-- Canary step 4 (Task 9): ground-truth table + gateway model monitor + metric queries.
-- Prereqs: PDM_SERVICE_V1 / PDM_SERVICE_V2 deployed with auto-capture, PDM_GATEWAY
-- created (infra/create_gateway.sql), and some traffic sent through the gateway
-- (scripts/simulate_traffic.py) so the inference logs exist.

-- 1. Ground-truth table for performance metrics.
--    IDs must be STRING and match the extra_columns (MACHINE_ID, DATE) sent in requests.
--    Label = did the machine fail the next day (FAILURE shifted -1 day), else 0.
CREATE OR REPLACE TABLE AI_DEMOS_PROD.IOT_PREDICTIVE_MAINTENANCE_MODEL_REGISTRY.PDM_GROUND_TRUTH AS
SELECT
  s.MACHINE_ID::string        AS MACHINE_ID,
  TO_VARCHAR(s.DATE)          AS DATE,
  COALESCE(f.FAILURE, 0)::number AS FAILURE_IN_1_DAY
FROM (
  SELECT DISTINCT MACHINE_ID, DATE
  FROM AI_DEMOS_PROD.IOT_PREDICTIVE_MAINTENANCE_FEATURE_STORE."MACHINE_SENSORS_LAG_FEATURES$1"
) s
LEFT JOIN (
  SELECT MACHINE_ID, DATEADD('day', -1, DATE) AS DATE, FAILURE
  FROM AI_DEMOS_PROD.IOT_PREDICTIVE_MAINTENANCE.MACHINE_FAILURES
) f
  ON s.MACHINE_ID = f.MACHINE_ID AND s.DATE = f.DATE;

-- 2. Gateway model monitor. Drift needs no ground truth; performance needs
--    GROUND_TRUTH + ID_COLUMNS (which must match the request extra_columns).
--    Single-output binary classification -> prediction/actual columns are inferred.
CREATE OR REPLACE MODEL MONITOR AI_DEMOS_PROD.IOT_PREDICTIVE_MAINTENANCE_MODEL_REGISTRY.PDM_GATEWAY_MONITOR WITH
  MODEL = AI_DEMOS_PROD.IOT_PREDICTIVE_MAINTENANCE_MODEL_REGISTRY.PREDICTIVE_MAINTENANCE_MODEL
  GATEWAY = AI_DEMOS_PROD.IOT_PREDICTIVE_MAINTENANCE_MODEL_REGISTRY.PDM_GATEWAY
  FUNCTION = 'predict'
  WAREHOUSE = PDM_WH_PROD
  REFRESH_INTERVAL = '1 minute'
  AGGREGATION_WINDOW = '1 hour'
  GROUND_TRUTH = AI_DEMOS_PROD.IOT_PREDICTIVE_MAINTENANCE_MODEL_REGISTRY.PDM_GROUND_TRUTH
  ID_COLUMNS = ('MACHINE_ID', 'DATE');

-- 3. Compare V1 vs V2 (metrics refresh ~1 min; UI: Models -> Gateways -> Monitoring).
--    IMPORTANT query rules that actually return rows:
--      * pass granularity '1 HOUR' explicitly (omitting defaults to invalid MINUTE)
--      * let start_time/end_time DEFAULT (explicit ranges can exclude the open bucket)
--      * pass SERVICE / BASE_SERVICE as UNQUOTED identifiers

-- Performance (F1) for each service:
SELECT * FROM TABLE(MODEL_MONITOR_PERFORMANCE_METRIC(
  'AI_DEMOS_PROD.IOT_PREDICTIVE_MAINTENANCE_MODEL_REGISTRY.PDM_GATEWAY_MONITOR',
  'F1_SCORE', '1 HOUR',
  SERVICE => AI_DEMOS_PROD.IOT_PREDICTIVE_MAINTENANCE_MODEL_REGISTRY.PDM_SERVICE_V1));

SELECT * FROM TABLE(MODEL_MONITOR_PERFORMANCE_METRIC(
  'AI_DEMOS_PROD.IOT_PREDICTIVE_MAINTENANCE_MODEL_REGISTRY.PDM_GATEWAY_MONITOR',
  'F1_SCORE', '1 HOUR',
  SERVICE => AI_DEMOS_PROD.IOT_PREDICTIVE_MAINTENANCE_MODEL_REGISTRY.PDM_SERVICE_V2));
-- (also valid: 'PRECISION', 'RECALL', 'CLASSIFICATION_ACCURACY', 'ROC_AUC')

-- Drift (PSI) of V2 vs V1 baseline on the prediction column:
SELECT * FROM TABLE(MODEL_MONITOR_DRIFT_METRIC(
  'AI_DEMOS_PROD.IOT_PREDICTIVE_MAINTENANCE_MODEL_REGISTRY.PDM_GATEWAY_MONITOR',
  'POPULATION_STABILITY_INDEX', 'FAILURE_IN_1_DAY_PREDICTION', '1 HOUR',
  SERVICE => AI_DEMOS_PROD.IOT_PREDICTIVE_MAINTENANCE_MODEL_REGISTRY.PDM_SERVICE_V2,
  BASE_SERVICE => AI_DEMOS_PROD.IOT_PREDICTIVE_MAINTENANCE_MODEL_REGISTRY.PDM_SERVICE_V1));

-- 4. Suspend / resume / drop:
-- ALTER MODEL MONITOR ...PDM_GATEWAY_MONITOR SUSPEND;
-- ALTER MODEL MONITOR ...PDM_GATEWAY_MONITOR RESUME;
-- DROP MODEL MONITOR IF EXISTS ...PDM_GATEWAY_MONITOR;
